### ISSUE TITLE
Add plugin validation to the builder

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/extension-builder#10]
Move the plugin validation code from https://github.com/jupyter/jupyterlab/blob/master/jupyterlab/index.js to here so the extension builder has immediate feedback.

**Comment by jasongrout** [comment]
It's probably a good idea _copy_ it and keep it there too.

**Comment by blink1073** [comment]
Well, keep it here and use it from there.

**Comment by jasongrout** [comment]
Sounds good.
