### ISSUE TITLE
Default loaders and custom loaders

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/extension-builder#42]
The extension builder has a bunch of loaders already enabled in `DEFAULT_LOADERS` as well as the `css-loader`. 

For extension builders, it may come as a surprise. In the case of widget packages, I have a list of loaders in a variable that I use for all the bundles (embedder, classic notebook, extension), which I cannot use for the labextension because it causes those that are also in DEFAULT_LOADERS to be called twice...

Do we need all these loaders enabled by default?

**Comment by SylvainCorlay** [comment]
I just opened it as a heads up since it bit me a couple of times already.

**Comment by jasongrout** [comment]
We're trying to cover the common cases, so people don't have to write a webpack file in the common case. Which loaders do you think would not be commonly used?

**Comment by jasongrout** [comment]
On the other hand, @SylvainCorlay, you can just set useDefaultLoaders to false: https://github.com/jupyterlab/extension-builder/blob/master/src/builder.ts#L163

**Comment by jasongrout** [comment]
See https://github.com/bloomberg/bqplot/pull/358 for an example.
