### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by OliverEvans96** [jupyterlab/extension-builder#52]
I see that the description says this package is deprecated, but I didn't see any other similar comments in the README. Is there another repo/doc that I should be looking at, or does some dust need to settle before the documentation catches up to the rapidly changing environment?

Thanks,
Oliver

**Comment by blink1073** [comment]
The building is all done on the user's machine now, using `jupyter lab build`.   The docs are [here](https://github.com/jupyterlab/jupyterlab/blob/master/docs/extensions_user.md).

**Comment by OliverEvans96** [comment]
Great, thanks!
