### ISSUE TITLE
Help with the new labextensions

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/extension-builder#53]
I am trying to build labextensions for JLab v0.25.0, and was wondering if there is an extension builder for building packages in the new way. I was previously using the deprecated extension builder, and those extensions are no longer compatible. 

I wanted some help, in understanding how the new labextensions are built. The documentation is not very extensive yet. So I built an npm package and that works fine, but I want to build several extensions and use them all with one install. Earlier in the extension builder I'd just mention the names of the extensions and it would create builds for them. Not very sure how I can bundle all these separate npm packages in one now.

Eg: I have two separate npm packages dummy1 and dummy2, and I want to put them in one npm package that can install both of them as labextensions.
Is there a video I can look at for the latest extensions?

**Comment by blink1073** [comment]
Hi @rsinha25, have you seen https://github.com/jupyterlab/jupyterlab/blob/master/docs/extensions_dev.md?  If you want one npm package that exports others, you can depend on those and re-export their plugins as part of the roll-up package.

**Comment by rsinha25** [comment]
Thanks! :)
